#!/bin/sh
#
# Author: Dennis Hodapp
# Filename: irc-start
# Requires: irssi
#
# Also notifies irssi stuff from fnotify

TERMINAL=${TERMINAL:-"gnome-terminal"}
SHELL=${SHELL:-"/usr/bin/bash"}
EXECUTE='irssi &> /dev/null'

$TERMINAL -x $SHELL -c $EXECUTE
